name: biomaapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"
  

dependencies:
  printing: ^5.3.0
  flutter:
    sdk: flutter
  provider: ^6.0.2
  intl: ^0.17.0
  http: ^0.13.3
  shared_preferences: ^2.0.6
  mask_text_input_formatter: ^2.1.0 
  flutter_svg: ^1.0.3
  form_field_validator: ^1.1.0
  google_nav_bar: ^5.0.5
 # flutter_chips_input: ^1.10.0
  brasil_fields: ^1.9.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
 
  scroll_to_index: ^3.0.1
  user_profile_avatar: ^0.1.2
  cached_network_image: ^3.2.1
  
  dependencies:
  flutter_localizations: 
    sdk: flutter
  localization: 2.1.0
  image_picker: ^0.8.5+3
  badges: ^2.0.3
  timelines: ^0.1.0
  url_launcher: ^6.1.4
  uni_links: ^0.5.1
  google_maps_flutter: ^2.1.9
  geolocator: ^9.0.1  
  flutter_launcher_icons: ^0.11.0
  grouped_list: ^5.1.2
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  share_plus: ^6.3.0
  qr_flutter: ^4.0.0
  flutter_native_splash: ^2.2.16
  google_maps_flutter_web: ^0.4.0+3
  textfield_tags: ^2.0.2
  incrementally_loading_listview: ^1.0.0
  fl_chart: ^0.62.0
  syncfusion_flutter_charts: ^21.2.4
  flutter_svg_provider: ^1.0.3
  carousel_slider: ^4.2.1
  pdf: ^3.2.0
  path_provider: ^2.0.15
  route_observer_mixin: ^1.7.0
  

  

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_speed_dial: ^6.0.0
  flutter_test:
    sdk: flutter
  table_calendar: ^3.0.6
#Para mudar o ICO tem que rodar flutter pub run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"

flutter_icons: 
  android: "launcher_icons"
  ios: true
  image_path: "assets/icons/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  #   assets:
  #    - asset: assets/images/biomaLogo.png
  assets:
    - assets/icons/
    - assets/imagens/
    - assets/fonts/
    - lib/i18n/
    
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
    - family: Anton
      fonts:
        - asset: assets/fonts/Anton-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages